package by.academy.task04mysql.entity;

public enum Name {
	JAMES, ROBERT, JOHN, MICHAEL, DAVID, WILLIAM, RICHARD, JOSEPH, THOMAS, CHARLES, MARY, PATRICIA,
	JENNIFER, LINDA, ELIZABETH, BARBARA, SUSAN, JESSICA, SARAH, KAREN
}
