package by.academy.task04sql.entity;

public enum Surname {
	SMITH, JOHNSON, WILLIAMS, BROWN, JONES, GARCIA, MILLER, DAVIS, RODRIGUEZ, MARTINEZ, HERNANDEZ,
	ANDERSON, MOORE, THOMPSON, WHITE, CLARK, ROBINSON, WALKER, YOUNG, CAMPBELL;
}
