package by.academy.pagination.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public final class PersonDTO {
    /**
     * unique identification number of person generated by database.
     */
    private Integer id;
    /**
     * name of person.
     */
    private String name;
    /**
     * surname of person.
     */
    private String surname;
}
